In [ ]:
import pandas as pd

In [ ]:
# !pip install tensorflow

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.19.0


In [ ]:
from tensorflow.keras.preprocessing.text import one_hot

In [ ]:
## sentences
sent= [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good'
]

In [ ]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [ ]:
# vocab size
voc_size=10000

**One hot representation**

In [ ]:
onehot_repr= [one_hot(words, voc_size)for words in sent]

In [ ]:
print(onehot_repr)

[[5325, 1217, 6351, 9043], [5325, 1217, 6351, 1588], [5325, 1681, 6351, 2987], [2852, 2181, 1397, 7151, 5832], [2852, 2181, 1397, 7151, 6154], [9029, 5325, 1907, 6351, 1471], [3526, 4117, 3971, 7151]]


**Word embedding representation**

In [ ]:
from tensorflow.keras.layers import Embedding , Input
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [ ]:
import numpy as np

This is used to set the length of all the sentences to the same length that is 8 in this scenario . This is called padding. It is achieved by adding zeroes in front or end
if zeroes are added in front it is called pre-padding and if the zeroes are added at the end it is called post-padding

It maked sure that the input size is fixed

In [ ]:
# Pre padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 5325 1217 6351 9043]
 [   0    0    0    0 5325 1217 6351 1588]
 [   0    0    0    0 5325 1681 6351 2987]
 [   0    0    0 2852 2181 1397 7151 5832]
 [   0    0    0 2852 2181 1397 7151 6154]
 [   0    0    0 9029 5325 1907 6351 1471]
 [   0    0    0    0 3526 4117 3971 7151]]


# Now we need to convert each and every value to vectors

In [ ]:
# Feature repr size (dimensions)
dim=10

In [ ]:
model= Sequential()
model.add(Input(shape=(sent_length,)))
model.add(Embedding(voc_size, 10))
model.compile('adam', 'mse')


In [ ]:
model.summary()


Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
print(model.predict(embedded_docs))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 176ms/step
[[[-2.48143319e-02 -1.61671638e-03 -3.71435285e-02  8.91153887e-03
   -8.72560591e-03 -3.58394757e-02  2.04889886e-02  3.17034982e-02
   -4.19639125e-02  4.52573188e-02]
  [-2.48143319e-02 -1.61671638e-03 -3.71435285e-02  8.91153887e-03
   -8.72560591e-03 -3.58394757e-02  2.04889886e-02  3.17034982e-02
   -4.19639125e-02  4.52573188e-02]
  [-2.48143319e-02 -1.61671638e-03 -3.71435285e-02  8.91153887e-03
   -8.72560591e-03 -3.58394757e-02  2.04889886e-02  3.17034982e-02
   -4.19639125e-02  4.52573188e-02]
  [-2.48143319e-02 -1.61671638e-03 -3.71435285e-02  8.91153887e-03
   -8.72560591e-03 -3.58394757e-02  2.04889886e-02  3.17034982e-02
   -4.19639125e-02  4.52573188e-02]
  [-1.17938295e-02 -1.67458132e-03 -2.34839562e-02  3.85753810e-05
    3.98940966e-03 -1.27750151e-02 -4.08183411e-03 -2.05645710e-03
   -1.64098628e-02 -1.12566352e-02]
  [-1.79804191e-02  6.20514154e-03  3.64664234e-02 -1.17623322e-02
    2.22307779e-02 -6.02423027e-03  4.401842

In [ ]:
embedded_docs[0]

array([   0,    0,    0,    0, 5325, 1217, 6351, 9043], dtype=int32)

In [ ]:
sent=[
    'The world is a better place',
    'Marvel series is my favourite movie',
    'I like DC movies',
    'the cat is eating the food',
    'Tom and Jerry is my favourite movie',
    'Python is my favourite programming language'
]

In [ ]:
df=pd.read_csv('/content/IMDB Dataset.csv')

In [ ]:
df

,review,sentiment
0,One of the other reviewers has mentioned that ...,positive
1,A wonderful little production. <br /><br />The...,positive
2,I thought this was a wonderful way to spend ti...,positive
3,Basically there's a family where a little boy ...,negative
4,"Petter Mattei's ""Love in the Time of Money"" is...",positive
...,...,...
49995,I thought this movie did a down right good job...,positive
49996,"Bad plot, bad dialogue, bad acting, idiotic di...",negative
49997,I am a Catholic taught in parochial elementary...,negative
49998,I'm going to have to disagree with the previou...,negative


In [ ]:
reviews=df['review']

In [ ]:
onehot_repr=[one_hot(words , voc_size)for words in reviews]

In [ ]:
len(max(onehot_repr))

101

In [ ]:
# padding
embedded_docs=pad_sequences(onehot_repr , padding='pre' , maxlen=110)

In [ ]:
embedded_docs

array([[9291, 5325, 1173, ..., 3526, 4352, 2751],
       [7183, 2971, 7257, ..., 1606, 6342, 2242],
       [3814, 8699, 7734, ..., 9126, 7294, 7984],
       ...,
       [7151, 5185, 5185, ..., 5767, 7146, 3114],
       [5471, 5978, 2011, ..., 2683, 4257,  203],
       [8336, 7313, 6812, ..., 3488, 8623, 8336]], dtype=int32)

In [ ]:
model2= Sequential()
model2.add(Input(shape=(110,)))
model2.add(Embedding(voc_size, 10))
model2.compile('adam', 'mse')

In [ ]:
model2.summary()

Model: "sequential_8"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)         │ (None, 110, 10)        │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model2.predict(embedded_docs)

1563/1563 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step


array([[[-0.00885534,  0.01352504,  0.03067582, ...,  0.00643431,
         -0.0230251 ,  0.02636582],
        [-0.01457524, -0.00100517,  0.01910373, ...,  0.0398531 ,
         -0.0336171 , -0.03891593],
        [ 0.04657543, -0.02896707,  0.00882531, ..., -0.01829048,
         -0.0077144 ,  0.04552895],
        ...,
        [-0.01509081, -0.03099161,  0.00868221, ...,  0.01241652,
         -0.03524889, -0.01295955],
        [-0.01296294,  0.04654587,  0.04827758, ...,  0.04705186,
          0.02424445,  0.04878298],
        [-0.02671061,  0.01542156, -0.00994345, ...,  0.03729946,
         -0.00697954, -0.04966391]],

       [[ 0.01139268,  0.01073427, -0.03813148, ...,  0.01546278,
         -0.02366617, -0.01997815],
        [ 0.03697619,  0.00693444, -0.00385374, ..., -0.02893643,
          0.0417353 , -0.00276238],
        [-0.02127909, -0.04060226,  0.03070704, ..., -0.03273108,
          0.04693253, -0.01276678],
        ...,
        [-0.01878159, -0.04399661,  0.00961854, ...,  